# exp_path: "/home/rdaneel/exp_aaai/"
exp_path: "/home/rdaneel/my_exp/"
ins_num: 25
time_limit: 60
plot_ci: false

f_weights:
  - 1.01
  - 1.02
  - 1.05
  - 1.10

maps:
  - name: random-32-32-20
    label: random
    scens:
      - even
    num_of_agents:
      - 20
      - 40
      - 60

solvers:
  - name: EECBS00
    label: 'EECBS'
    color: 'grey'
    marker: 'P'
    w: 1.02
    mth: -1
    T_N: -1
    T_i: -1

  - name: NEECBS
    label: 'NEECBS (b=1)'
    color: 'green'
    marker: 's'
    w: 1.02
    mth: 1
    T_N: -1
    T_i: -1

  - name: NEECBS1
    label: 'NEECBS (b=1,Outer:WDG)'
    color: 'deepskyblue'
    marker: 'o'
    w: 1.02
    mth: 1
    T_N: -1
    T_i: -1

  - name: NEECBS3
    label: 'NEECBS (b=25,Outer:WDG)'
    color: 'orange'
    marker: '^'
    w: 1.02
    mth: 25
    T_N: -1
    T_i: -1
